OpenCyphal/libcanard

src/Makefile, src/canard.c, src/canard.h, src/canard_internals.h, src/canard_test.c, src/crc_test.c
Included is my current working version of libcanard. canardReadRxTransferPayload is the only missing function right now. Recent updates to the design document have also not been implemented (ftp://pkir.net/libcanard.diff). canard_test.c, based on simple_sensor_node is what I've been using to test the library. It sends 3 data types on the can interface. There's also a function, random_drop(x), called on the bottom of the send thread that will randomly drop a frame. Set that to the probability you want frames dropped, 0 if you dont want anything dropped. Right now canard_test just prints out the data received from the library.
To do:
implement crc checking
ignore incomplete transfers (probably has to do with the above)
ask any questions!
=> Implement Libcanard Library

canard.c
In current master version of library if NULL will be provided as payload, message will not be sent even if payload length is 0.
Additional check for payload length fixes this bug.
=> Fix for sending of 0-length messages

canard.c
I noticed allocator overflows caused hard fault errors during heavy CAN bus usage, caused by missing null checks after allocation requests.
I also validated that now, the entire call hierarchy for allocateBlock checks for allocation failures to avoid null pointer dereferencing.
=> Allocation failure checks

.gitignore, DESIGN.md, canard.c, canard.h, canard_internals.h, tests/CMakeLists.txt, tests/demo.c, tests/test_init.cpp
The new function `canardGetUserReference()` will be useful when the library instance requires integration into larger data structures, such as C++ objects. Having a user-specific reference will enable the user code to route the callbacks correctly. Example:
```c++
static void callbackFromTheLibraryTrampoline(CanardInstance* const ins, Stuff stuff)
{
assert(ins->user_reference != nullptr);
reinterpret_cast<MyClass*>(ins->user_reference)->callbackFromTheLibrary(stuff);
}
```
=> Extended the library API with a new function canardGetUserReference()

drivers/nuttx/canard_nuttx.c
Hi Pavel,
This patch is needed to get libcanard working on NuttX.
=> Fix new NuttX CAN Bus header location

canard.h
Added a new macro `CANARD_STATIC_ASSERT()` which expands into the standard `static_assert()` if the current language is C11 or C++14 or newer. Using this macro to ensure that the struct sizes are correct.
As per the design document, 64-bit platforms are not supported: https://github.com/UAVCAN/libcanard/blob/master/DESIGN.md#feature-set
=> Abort build if the platform is not supported

.travis.yml, canard.c, canard.h, canard_internals.h, drivers/stm32/canard_stm32.h, tests/CMakeLists.txt, tests/catch/catch.hpp, tests/catch/test_main.cpp, tests/demo.c, tests/stm32/test_can_timings.cpp, tests/test_crc.cpp, tests/test_float16.cpp, tests/test_memory_allocator.cpp, tests/test_scalar_encoding.cpp
* Fixed several dozen complaints from clang-tidy (somebody should configure it to run via CI).
* Added a couple more static asserts and fixed an issue with the static assertion macro.
*  Enabled all sensible warnings available in GCC 7 / Clang 5 with `-Werror`.
* Removed GTest, which I came to dislike for clumsiness, in favor of Catch2.
* Prettified the Travis CI script; implemented a Clang 5 and GCC 7 builds.
This changeset does not affect the API or the logic of the library.
=> Code robustness improvements

canard.c, canard.h, canard_internals.h, drivers/socketcan/socketcan.c, drivers/socketcan/socketcan.h, drivers/stm32/_internal_bxcan.h, drivers/stm32/canard_stm32.c, drivers/stm32/canard_stm32.h, tests/demo.c
This is the PR that I advertised here https://github.com/UAVCAN/libcanard/pull/48
=> Removed all native integral types in favor of stdint in order to improve portability and compliance with high-integrity coding standards

canard.h
Fixed compatibility issue when checking struct size in assert
https://github.com/UAVCAN/libcanard/issues/51
=> Fixed assert sizeof compatibility issue

.gitignore, dsdl_compiler/libcanard_dsdl_compiler/data_type_template.tmpl
#58 Constants for lengths of arrays are now generated. 
To distinguish between constants for dynamic and static arrays, different suffixes are used.
For dynamic arrays, the constants will be suffixed with "_MAX_LENGTH", while for static arrays "_LENGTH" is used.
=> Added constants for length of arrays in header files.

dsdl_compiler/libcanard_dsdl_compiler/data_type_template.tmpl
If two constants in a service message have the same name, the first one is lost (redefined by the second one)
This path prefix the constants with REQUEST or RESPONSE like any other fields.
--
Found with the ReportBackSoldier service of libuavcan test files
=> Fix issue with service constants in dsdl compiler

dsdl_compiler/libcanard_dsdl_compiler/code_type_template.tmpl
Depending on the dsdl definition files, the libcanard compiler can generate code with warnings. This patch remove all warnings for dsdl files found in libuavcan repository (tests, and standard uavcan)/
What it does:
- mark a lot of function parameters as maybe unused, to suppress gcc warning
- use two differents macros for signed and unsigned saturation
=> Fix build warnings

README.md, canard.h
The option is given to the user of providing the `canard_build_config.h` header file with custom overrides; this is enabled by defining the `CANARD_ENABLE_CUSTOM_BUILD_CONFIG ` flag.
=> Create separate header file for defining the build configuration

dsdl_compiler/libcanard_dsdl_compiler/code_type_template.tmpl
this removes the void* cast when calling encode_internal and
decode_internal for compounts. The void* cast causes a -fpermissive
error when built with C++
=> dsdlc_compiler: fixed building of headers with C++

dsdl_compiler/libcanard_dsdl_compiler/code_type_template.tmpl, dsdl_compiler/libcanard_dsdl_compiler/data_type_template.tmpl
the v0 non-TAO support didn't work correctly any way, it can get false matches which causes incorrect parsing
=> dsdl_compiler: removed non-TAO v0 support

drivers/stm32/README.md
I have personally verified CAN1 to be fully functional on the F303 series.
=> Added STM32F303 as a tested MCU.

dsdl_compiler/libcanard_dsdlc
Removes old reference to pyuavcan's directory and instead uses pydsdl's.
=> Use pydsdl's directory instead of pyuavcan's

dsdl_compiler/libcanard_dsdl_compiler/__init__.py, dsdl_compiler/libcanard_dsdlc
Fixed bug where parsing failed if using unions in request/responses. Add option to allow unregulated fixed port IDs to DSDL compiler from CLI.
=> Bugfix, and add support of parsing unregulated fixed port IDs

tests/test_rxerr.cpp
Let's merge this into master then include it in #92 as well.
I didn't bother adding tests for priority different from 0 at this point as the header changes is going into the uavcan v1.0 branch pretty soon anyway and that seemed like a just as good point in time to do it.
=> Bugfix priority field position in test

canard.c, canard_internals.h
I've received an email notifying me of this bug. We weren't aware of it because we don't have unit tests here. The TX queue was prioritized improperly because of this issue.
This fix should be cherry-picked into uavcan-v1.0 as well.
=> Fixed the argument order in isPriorityHigher()

.gitignore, .travis.yml, DESIGN.md, canard.c, canard.h, tests/test_rxerr.cpp
This is a start of updating the ID header to match the new format for v1.0. Note: It could be that I have missed some parts which also must be updated related to the new header format, or that I have made some mistakes. Therefore, I would appreciate that you check my changes thoroughly. 
These changes were originally included in #96, but we chose to split it out to a separate PR.
=> Start of updating CAN ID header format to match v1.0

canard.c, canard.h
Forgot to change fields for service IDs from uint8 to uint16 in the previous PR. This caused the ID to overflow.
=> Fix bug where service IDs were sliced due to overflow

dsdl_compiler/libcanard_dsdl_compiler/data_type_template.tmpl
=> Generate constants also for "empty" files with no fields.

dsdl_compiler/libcanard_dsdl_compiler/code_type_template.tmpl, dsdl_compiler/libcanard_dsdl_compiler/data_type_template.tmpl
My attempt of removing TAO support #108 . I think I have done it correctly, but please verify that the decode and encode functionality of autogenerated code is correct. 
Example of uavcan/node/Record: [Record.1.0.txt](https://github.com/UAVCAN/libcanard/files/3035273/Record.1.0.txt)
=> Removed TAO in serialization code.

dsdl_compiler/libcanard_dsdl_compiler/code_type_template.tmpl
In using dynamic arrays in my project, I came across a major issue where the first two elements in an array would be decoded correctly, but any element after that was mangled and useless.
After a few hours of debugging, (and some major help from some friends) we traced it back to the DSDLC-generated decode_internal functions.
Essentially, we found that the loop that decodes each element in the array adds the value returned by the decode_internal function of the internal data structure, which returns the cumulative offset expands way too fast. The offset value is essentially added to itself *and* the incremented value each time, which means that new elements are essentially placed in arbitrary memory locations.
The encode fix hasn't been entirely tested, but looking at the code it follows …
=> Fix DSDL Compiler Dynamic Array Encoding/Decoding Issues

README.md, libcanard/canard.h
```
int8_t canardRxSubscribe(CanardInstance* const       ins,
const CanardTransferKind    transfer_kind,
const CanardPortID          port_id,
const size_t                payload_size_max,
const CanardMicrosecond     transfer_id_timeout_usec,
CanardRxSubscription* const out_subscription)
```
Maybe we need `transfer_id_timeout_usec` this param for this function.
=> Fix some bugs in readme doc.

libcanard/canard.c
This PR allows ASSERTs to be on while using UAVCANv0
=> Fix hardcoded initial toggle state requirement

.idea/dictionaries/pavel.xml, .travis.yml, README.md, libcanard/canard.c, libcanard/canard.h, libcanard/canard_dsdl.c, tests/CMakeLists.txt, tests/exposed.hpp, tests/helpers.hpp, tests/test_dsdl.cpp, tests/test_private_rx.cpp, tests/test_private_tx.cpp, tests/test_public_roundtrip.cpp, tests/test_public_rx.cpp, tests/test_public_tx.cpp, tests/test_self.cpp
- Update CI to Ubuntu 20.04, GCC 10, Clang 10 (also fix a couple of minor nitpicks from the new clang-tidy)
- Implement https://github.com/UAVCAN/specification/issues/94
- Implement https://github.com/UAVCAN/specification/issues/90
- Fix the NaN handling issues discovered by Scott in https://github.com/UAVCAN/nunavut/pull/115
- Bump the version number to **v1.0**. A long way from the first commit https://github.com/UAVCAN/libcanard/commit/6d7d39eae1d399da9bb4f62e292a5e70cbffd75d pushed in 2015.
This PR will not be merged and may incur changes until https://github.com/UAVCAN/specification/pull/97 is approved.
I debated whether it's worth [renaming "subscription" into "listener" to avoid confusion](https://forum.uavcan.org/t/how-to-use-services-correctly-in-libcanard/927/2?u=pavel.kirienko): …
=> Libcanard v1.0

.idea/dictionaries/pavel.xml, README.md, libcanard/canard_dsdl.c, libcanard/canard_dsdl.h
This is a minor changeset. The code changes do not affect the semantics so the minor version is not bumped.
=> Mention Nunavut in the docs and port improvements to canardCopyBits() from Nunavut

.travis.yml, CONTRIBUTING.md, libcanard/.clang-tidy, libcanard/canard.c, libcanard/canard.h, libcanard/canard_dsdl.c, tests/CMakeLists.txt, tests/exposed.hpp, tests/helpers.hpp, tests/test_public_roundtrip.cpp, tests/test_public_rx.cpp
- Fix #163
- Update Clang-Tools to v11:
- More consistent autoformatting (hide whitespace changes to declutter the diff)
- New checks in clang-tidy
- Remove redundant declarations before static functions by improving the build flag handling in the test suite
- CI broke due to external factors; this PR fixes it
- Bump minor version number
Backward compatibility not affected
Context https://forum.uavcan.org/t/libcanard-calling-canardrxaccept-handler-in-o-1-time/1257
=> Add canardRxAccept2(), fix #163

libcanard/canard.c, libcanard/canard.h, tests/test_public_rx.cpp
As discussed in https://forum.uavcan.org/t/libcanard-listing-active-canardrxsubscription/1266
=> Expose CanardRxSubscription

README.md, libcanard/canard.c, libcanard/canard.h, tests/CMakeLists.txt, tests/test_public_filters.cpp
Briefly tested all 3 functions on a test project with yakut. Appears to work, and it's super simple.
@pavel-kirienko Does it make more sense from an API perspective to use the CanardInstance itself as an argument for the service generator and pull the local node id from that?
Closes #169
=> add acceptance filter configuration helper

canard.c, tests/test_rxerr.cpp
Without this check we can crash here https://github.com/UAVCAN/libcanard/blob/legacy-v0/canard.c#L340-L357 
This happen because when processing single frame transfer we check that `state->buffer_blocks == NULL`
But if inside multi frame transfer we receive  single frame transfer this assert can happen.
This problem happened in real environment.
=> Fix crush single message inside long message

.github/workflows/main.yml, libcanard/canard.c, libcanard/canard.h, tools/Dockerfile
=> misra: remove flexible array

.github/workflows/main.yml, libcanard/canard.c
During building the `canard.c` with arm compiler with `Wcast-align` flag, few warnings appear.
To reproduce these warnings, you may type the command below:
```bash
arm-none-eabi-gcc libcanard/canard.c -c -Wcast-align
```
It returns the following warnings:
```c
libcanard/canard.c: In function 'txAVLPredicate':
libcanard/canard.c:327:45: warning: cast increases required alignment of target type [-Wcast-align]
327 |     const CanardTxQueueItem* const other  = (const CanardTxQueueItem*) node;
|                                             ^
libcanard/canard.c: In function 'rxSubscriptionPredicateOnPortID':
libcanard/canard.c:948:38: warning: cast increases required alignment of target type [-Wcast-align]
948 |     const CanardPortID  other     = ((const CanardRxSubscription*) node)->port_id;
| …
```
=> Fix wcast align warnings on ARM

tests/helpers.hpp
Fix unused variable warnings and sign conversion warning in test helpers.
#201
=> Fix warnings in test helpers

tests/CMakeLists.txt
* currently enabled on 64 bit unit test build. (edit: sanitizers added to x32 build by beaf0a8)
* silently falls back if -fsanitize=undefined support is not detected
* verifies bug-203 fix
=> add add sanitizers to unit test cmake build

README.md, libcanard/canard.c, libcanard/canard.h, tests/test_private_rx.cpp, tests/test_public_rx.cpp
=> Amend the transfer reassembly state machine and prepare v3.1 release

README.md, libcanard/canard.c, libcanard/canard.h, tests/exposed.hpp, tests/helpers.hpp, tests/test_private_rx.cpp, tests/test_public_rx.cpp
This is a step towards improving the transfer reassembler.
This changeset also renames `redundant_transport_index` as `redundant_iface_index` for consistency with the other implementations; this change is not visible at the API level.
=> Refactor the transfer reassembly state machine to enhance its maintainability and robustness

README.md, libcanard/canard.c
During the integration of the `libcanard` into a project based on [ChibiOS](https://www.chibios.org) I want to change `CANARD_ASSERT` from the default `assert` to ChibiOS `osalDbgCheck`. It is done with the next C defines `-DCANARD_ASSERT=osalDbgCheck -DCANARD_CONFIG_HEADER=\"${BINDINGS_DIR}/canard/canard_config.h\"`, there to prevent implicit declaration warnings I unutilized `CANARD_CONFIG_HEADER` by providing a `canard_config.h` file with the following content:
```
#include "osal.h"
```
But because of `#include "_canard_cavl.h"` and `#    include CANARD_CONFIG_HEADER` order in `canard.c` I still get implicit declaration warnings:
```
Compiling canard.c
../../ext/OpenCyphal/libcanard/libcanard/_canard_cavl.h: In function 'cavlPrivateRotate':
<command-line>: warning: implicit declaration …
```
=> Introduce internal includes section to avoid potential implicit declaration warnings

libcanard/canard.c, libcanard/canard.h
- added one more case when it's allowed to "restart" transfer reassembly with different transport interface
=> Fix for the "Improve RPC Client Response RX pipeline" issue # 228

README.md, libcanard/canard.c, libcanard/canard.h, tests/exposed.hpp, tests/helpers.hpp, tests/test_private_rx.cpp, tests/test_public_roundtrip.cpp, tests/test_public_rx.cpp, tests/test_public_tx.cpp, tests/test_self.cpp
- Extended `CanardTxQueueItem` with extra `allocated_size` field to remember original size allocated for the item (and its embedded payload).
- Extended `CanardRxTransfer` with extra `allocated_size` field to report to the client original size allocated for the payload buffer (which is normally equal to session `extent`).
=> Fixed issue #216 "canardMemFree must provide size"

.github/workflows/main.yml, libcanard/canard.c, libcanard/canard.h, tests/exposed.hpp, tests/helpers.hpp, tests/test_public_roundtrip.cpp, tests/test_public_tx.cpp
`canardTxPeek` now returns mutable item - needed for payload ownership transfer.
=> `canardTxPeek` now returns mutable item

MIGRATION_v3.x_to_v4.0.md, README.md, libcanard/_canard_cavl.h, libcanard/canard.c, libcanard/canard.h, tests/helpers.hpp, tests/test_public_tx.cpp
- eliminated struct/enum typedef-s
- added migration guide
=> v4 typedefs and migration guide

MIGRATION_v3.x_to_v4.0.md, libcanard/canard.c, libcanard/canard.h, tests/helpers.hpp, tests/test_public_tx.cpp
- added new `canaraTxPoll` and its `CanardTxFrameHandler`
- updated migration guide
=> v4 tx poll

.github/workflows/main.yml, .idea/dictionaries/project.xml, MIGRATION_v3.x_to_v4.0.md, README.md, libcanard/.clang-tidy, libcanard/_canard_cavl.h, libcanard/canard.c, libcanard/canard.h, tests/.clang-tidy, tests/CMakeLists.txt, tests/exposed.hpp, tests/helpers.hpp, tests/test_private_cavl.cpp, tests/test_private_rx.cpp, tests/test_public_roundtrip.cpp, tests/test_public_rx.cpp, tests/test_public_tx.cpp, tests/test_self.cpp
I want to keep the upcoming v4 changes on the main branch for visibility. We are not going to be publishing this release yet, though.
Changes:
- Fixed issue #216 (#233):
- Extended `CanardTxQueueItem` with extra `allocated_size` field to remember original size allocated for the item (and its embedded payload).
- Extended `CanardRxTransfer` with extra `allocated_size` field to report to the client original size allocated for the payload buffer (which is normally equal to session `extent`).
- New memory API for the TX pipeline only -- #225 #234 (not RX yet). Introduced new memory related types:
- `CanardMemoryAllocate`
- `CanardMemoryDeallocate`
- `CanardMemoryDeleter`
- `CanardMemoryResource`
- Fix potential memory leak in tests
- Introduce CanardPayload #235 
- added `struct …
=> Merge v4 into main

README.md
Since v4 has major changes, the readme document needs to be updated synchronously.
=> Fix errors in the readme document
